version: '3'

services:
  service_a:
    container_name: service_a
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - service_b
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - dockernet

  service_b:
    container_name: service_b
    build:
      context: ./otherservice
      dockerfile: Dockerfile
    networks:
      - dockernet

networks:
  dockernet:
    driver: bridge